server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8     # 连接池中的最小空闲连接
        min-idle: 0     # 连接池中的最大空闲连接
        max-active: 40  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 5000       # 连接超时时间
    password:           # Redis服务器连接密码